Container pipeline overhaul
redlib-org/redlib pull request #59
Opened 2024-02-24 23:04 UTC by nohoster

Hello, I decided to optimize the way the container is being build. Currently is really slow since it has to do a fresh compilation every time and also it's using emulation for the arm builds.

Instead I decided to split the process. First compile the redlib binary using cross compilation. This takes only 3 to 4 minutes. And then just copy this binary into a container.

This also allows the building process to reuse dependency cache.

The whole process takes less than 4 minutes in comparison to the 15 to 30 minutes of the current pipeline which is quite an improvement. It also produces a single redlib:latest multiarch container, so there is no need for different tags.

The only detail is that I'm using releases to save the binaries and I'm using the DATE-TIME as the release name since there is no app version updates. You can check the result in my repo.
If you don't like that I can change it into a single pipeline and copy the binary inside the pipeline.

2024-02-28 20:08 UTC, sigaloid commented on .github/workflows/main-docker.yml
> -          readme_file: 'README.md'
Looks great, but is there a reason this cannot be added alongside these changes? It's convenient to upload the README on new releases.

2024-02-28 23:55 UTC, nohoster commented on .github/workflows/main-docker.yml
> -          readme_file: 'README.md'
Sorry, I forgot that part. Although I must say that with the current setup and with this new pipeline, changes to the README are not being pushed to Quay.io. You can check how the new changes to the README didn't get pushed.

2024-02-29 01:48 UTC, sigaloid commented on .github/workflows/main-docker.yml
> -          readme_file: 'README.md'
Yep - as per below lines, `.MD` updates don't rebuild (and subsequently don't run the push). I'm okay with this, as readme changes don't necessarily have to be pushed to the repo until we change some code somewhere.

2024-02-29 01:55 UTC, sigaloid requested changes

2024-02-29 01:55 UTC, sigaloid commented on .github/workflows/build-artifacts.yaml
> +      #   run: echo "VERSION=$(cargo metadata --format-version 1 --no-deps | jq .packages[0].version -r | sed 's/^/v/')" >> "$GITHUB_OUTPUT"
I think we'd be better off using this especially because other packaging solutions may use the version already to identify new releases

2024-02-29 01:55 UTC, sigaloid commented on .github/workflows/main-docker.yml
> +          registry: ghcr.io
Should be updated to quay.io as we don't have a ghcr.io registry entry
```suggestion
          registry: quay.io
```

2024-02-29 01:55 UTC, sigaloid commented on .github/workflows/main-docker.yml
> +      - name: Oush README to Quay.io
```suggestion
      - name: Push README to Quay.io
```

2024-02-29 01:55 UTC, sigaloid commented on Dockerfile
We should probably leave the behavior of building the way that it is. We have the compose for those who want to run it normally without building (and the corresponding compose-dev for those who want to build).

2024-03-03 18:45 UTC, nohoster commented on Dockerfile
In that case we can just leave the current Dockerfiles and rename them to Dockerfile-dev. I'm sure people will benefit from having the compiled binaries. But in any case I understand is not an important change anyways.

2024-03-05 01:02 UTC, merged

2024-03-05 23:02 UTC, chowder commented
Took me a while to find out today why my changes weren't being reflected in my development containers... :'(

2024-09-17 10:17 UTC, master-hax commented
>Currently is really slow since it has to do a fresh compilation every time and also it's using emulation for the arm builds.

FYI there are fixes for this, we did not have to throw away the working Dockerfile and replace it with one that's a glorified link to github.

one example is https://github.com/libreddit/libreddit/pull/751 where i fixed the fresh compilation issue for the arm builds

2024-09-17 18:20 UTC, sigaloid commented
If you want to do another overhaul to the actions, I wouldn't be opposed to merging - there's been some struggles since this PR in some places. Open an issue describing your motivations and a PR, and I'll take a look. I'm not skilled in GHA in general so I defer to others generally.

2026-03-29 19:49 UTC, evrial commented on Dockerfile
> +RUN curl -L https://github.com/redlib-org/redlib/releases/latest/download/redlib-${TARGET}.tar.gz | \
That's not a clever change